export const Permissions = {
  ADMINISTRATOR: "Administrator",
  CREATE_INSTANT_INVITE: "Create invitations",
  KICK_MEMBERS: "Kick members",
  BAN_MEMBERS: "Ban members",
  MANAGE_CHANNELS: "Manage channels",
  MANAGE_GUILD: "Manage server",
  ADD_REACTIONS: "Add reactions",
  VIEW_AUDIT_LOG: "View Audit log",
  PRIORITY_SPEAKER: "Priority speaker",
  STREAM: "Video/Streams",
  VIEW_CHANNEL: "View channel",
  SEND_MESSAGES: "Send messages",
  SEND_TTS_MESSAGES: "Отправлять TTS сообщения",
  MANAGE_MESSAGES: "Manage messages",
  EMBED_LINKS: "Embed links",
  ATTACH_FILES: "Attach files",
  READ_MESSAGE_HISTORY: "Read message history",
  MENTION_EVERYONE: "Mention @everyone, @here, and all roles",
  USE_EXTERNAL_EMOJIS: "Use external emojis",
  VIEW_GUILD_INSIGHTS: "View server insights",
  CONNECT: "Connect",
  SPEAK: "Speak",
  MUTE_MEMBERS: "Mute members",
  DEAFEN_MEMBERS: "Defean members",
  MOVE_MEMBERS: "Move members",
  USE_VAD: "Use Voice activity",
  CHANGE_NICKNAME: "Change nickname",
  MANAGE_NICKNAMES: "Manage nicknames",
  MANAGE_ROLES: "Mangae roles",
  MANAGE_WEBHOOKS: "Manage webhooks",
  MANAGE_EMOJIS: "Manage emoji",
};
